apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  selector:
    matchLabels:
      app: inventory
  replicas: 3
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - image: inventory:1.0
          name: inventory-api
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo
          name: mongo-db
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    run: inventory-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: inventory
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    run: mongo-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongo